name: gradle test
on:
  push:
    branches:
      - main
  workflow_dispatch: # enables "Run workflow" button
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: gradle
      - uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew test